import { createHash } from "node:crypto";
import path from "node:path";

import { sortByStableKey, stableStringify } from "@power-exit/ir";

import {
  generationPlanSchema,
  type GeneratedArtifact,
  type FunctionsGenerationPlanDetails,
  type GenerationManualReviewItem,
  type GenerationPlan,
  type GenerationPlanAction,
  type GenerationUnsupportedFeature,
  type GenerationWarning,
  type SqlGenerationPlanDetails
} from "./contracts";

const generatedFileMarkerLines = [
  "Generated by Power Exit.",
  "Do not edit directly unless you intend to own the generated file."
] as const;

const markerTextPlain = generatedFileMarkerLines.join("\n");

const markerPrefixByExtension = (filePath: string): string | undefined => {
  const extension = path.extname(filePath).toLowerCase();
  if (extension === ".json") {
    return undefined;
  }

  if (extension === ".md") {
    return `<!-- ${generatedFileMarkerLines[0]} -->\n<!-- ${generatedFileMarkerLines[1]} -->\n\n`;
  }

  if (extension === ".sql") {
    return `-- ${generatedFileMarkerLines[0]}\n-- ${generatedFileMarkerLines[1]}\n\n`;
  }

  if ([".ts", ".tsx", ".js", ".jsx", ".css", ".scss", ".less"].includes(extension)) {
    return `/* ${generatedFileMarkerLines[0]} */\n/* ${generatedFileMarkerLines[1]} */\n\n`;
  }

  return `# ${generatedFileMarkerLines[0]}\n# ${generatedFileMarkerLines[1]}\n\n`;
};

export interface ExistingFileState {
  path: string;
  content: string;
}

export interface PlanGenerationInput {
  artifacts: GeneratedArtifact[];
  existingFiles: ExistingFileState[];
  force: boolean;
  warnings: GenerationWarning[];
  unsupportedFeatures: GenerationUnsupportedFeature[];
  formulaHotspots?: GenerationPlan["formulaHotspots"];
  manualReviewItems?: GenerationManualReviewItem[];
  sqlPlan?: SqlGenerationPlanDetails | null;
  functionsPlan?: FunctionsGenerationPlanDetails | null;
}

export interface PlannedArtifactWrite {
  path: string;
  content: string;
  action: GenerationPlanAction;
}

export interface PlanGenerationResult {
  plan: GenerationPlan;
  writes: PlannedArtifactWrite[];
}

const withGeneratedMarker = (filePath: string, content: string): string => {
  const markerPrefix = markerPrefixByExtension(filePath);
  if (!markerPrefix) {
    return content;
  }

  if (hasGeneratedFileMarker(content)) {
    return content;
  }

  return `${markerPrefix}${content}`;
};

export const hasGeneratedFileMarker = (content: string): boolean => {
  const markerWindow = content.split(/\r?\n/).slice(0, 6).join("\n");
  return generatedFileMarkerLines.every((line) => markerWindow.includes(line));
};

export const computeContentHash = (content: string): string =>
  createHash("sha256").update(content, "utf-8").digest("hex");

const collectParentDirectories = (filePath: string): string[] => {
  const directories: string[] = [];
  let current = path.posix.dirname(filePath);
  while (current !== "." && current !== "/" && current.length > 0) {
    directories.push(current);
    current = path.posix.dirname(current);
  }

  return directories;
};

const deriveManualReviewItems = (
  plannedFiles: GenerationPlan["plannedFiles"],
  skippedFiles: GenerationPlan["skippedFiles"],
  inputItems: GenerationManualReviewItem[]
): GenerationManualReviewItem[] => {
  const reviewItems: GenerationManualReviewItem[] = [...inputItems];
  skippedFiles.forEach((entry) => {
    const matchingFile = plannedFiles.find((file) => file.path === entry.path);
    reviewItems.push({
      id: `review:conflict:${entry.path}`,
      category: "file-conflict",
      severity: "medium",
      message: entry.reason,
      relatedPaths: [entry.path],
      sourceArtifactIds: matchingFile?.sourceArtifactIds ?? []
    });
  });

  return sortByStableKey(reviewItems, (item) => `${item.id}:${item.category}`);
};

const createConflictWarning = (artifact: GeneratedArtifact): GenerationWarning => ({
  code: "GENERATION_FILE_CONFLICT_SKIPPED",
  message: `Skipped "${artifact.filePath}" because an existing file differs. Use --force to overwrite.`,
  severity: "warning",
  confidence: 0.8,
  sourceArtifactIds: artifact.sourceArtifactIds,
  sourceLocation: artifact.filePath,
  provenance: artifact.provenance
});

export const planGeneration = (input: PlanGenerationInput): PlanGenerationResult => {
  const existingByPath = new Map(
    input.existingFiles.map((entry) => [entry.path, entry.content] as const)
  );
  const accumulatedWarnings: GenerationWarning[] = [...input.warnings];
  const plannedFiles: GenerationPlan["plannedFiles"] = [];
  const skippedFiles: GenerationPlan["skippedFiles"] = [];
  const overwrittenFiles: GenerationPlan["overwrittenFiles"] = [];
  const writes: PlannedArtifactWrite[] = [];
  const plannedDirectories = new Set<string>();
  const sortedArtifacts = sortByStableKey(input.artifacts, (artifact) => artifact.filePath);

  sortedArtifacts.forEach((artifact) => {
    const contentWithMarker = withGeneratedMarker(artifact.filePath, artifact.content);
    const existingContent = existingByPath.get(artifact.filePath);
    const nextHash = computeContentHash(contentWithMarker);
    const action: GenerationPlanAction =
      existingContent === undefined
        ? "create"
        : existingContent === contentWithMarker
          ? "unchanged"
          : input.force
            ? "overwrite"
            : "skip";
    const fileWarnings = sortByStableKey(artifact.warnings, (warning) => `${warning.code}:${warning.message}`).map(
      (warning) => ({
        code: warning.code,
        message: warning.message
      })
    );

    plannedFiles.push({
      path: artifact.filePath,
      artifactType: artifact.artifactType,
      sourceArtifactIds: sortByStableKey(Array.from(new Set(artifact.sourceArtifactIds)), (value) => value),
      action,
      contentHash: nextHash,
      confidence: artifact.confidence,
      warnings: fileWarnings
    });

    collectParentDirectories(artifact.filePath).forEach((directory) => plannedDirectories.add(directory));

    if (action === "create" || action === "overwrite") {
      writes.push({
        path: artifact.filePath,
        content: contentWithMarker,
        action
      });
    }

    if (action === "skip") {
      skippedFiles.push({
        path: artifact.filePath,
        reason: "Existing file differs from generated content and overwrite was not forced.",
        contentHash: nextHash
      });
      accumulatedWarnings.push(createConflictWarning(artifact));
    }

    if (action === "overwrite" && existingContent !== undefined) {
      overwrittenFiles.push({
        path: artifact.filePath,
        previousContentHash: computeContentHash(existingContent),
        nextContentHash: nextHash
      });
    }
  });

  const orderedPlannedFiles = sortByStableKey(plannedFiles, (file) => file.path);
  const orderedSkipped = sortByStableKey(skippedFiles, (file) => file.path);
  const orderedOverwritten = sortByStableKey(overwrittenFiles, (file) => file.path);
  const orderedWarnings = sortByStableKey(accumulatedWarnings, (warning) => `${warning.code}:${warning.message}`);
  const orderedUnsupported = sortByStableKey(
    input.unsupportedFeatures,
    (feature) => `${feature.severity}:${feature.featureType}:${feature.sourceLocation}`
  );
  const orderedHotspots = sortByStableKey(input.formulaHotspots ?? [], (hotspot) => {
    const controlLabel = hotspot.control ?? "(screen)";
    return `${hotspot.screen}:${controlLabel}:${hotspot.property}:${hotspot.generatedStubName}`;
  });
  const orderedManualReview = deriveManualReviewItems(
    orderedPlannedFiles,
    orderedSkipped,
    input.manualReviewItems ?? []
  );
  const orderedDirectories = sortByStableKey(Array.from(plannedDirectories), (directory) => directory);
  const summary = {
    totalPlannedFiles: orderedPlannedFiles.length,
    totalPlannedDirectories: orderedDirectories.length,
    creates: orderedPlannedFiles.filter((file) => file.action === "create").length,
    overwrites: orderedPlannedFiles.filter((file) => file.action === "overwrite").length,
    skips: orderedPlannedFiles.filter((file) => file.action === "skip").length,
    unchanged: orderedPlannedFiles.filter((file) => file.action === "unchanged").length,
    warnings: orderedWarnings.length,
    unsupportedFeatures: orderedUnsupported.length,
    formulaHotspots: orderedHotspots.length,
    manualReviewItems: orderedManualReview.length
  } as const;

  const plan = generationPlanSchema.parse({
    plannedFiles: orderedPlannedFiles,
    plannedDirectories: orderedDirectories,
    skippedFiles: orderedSkipped,
    overwrittenFiles: orderedOverwritten,
    warnings: orderedWarnings,
    unsupportedFeatures: orderedUnsupported,
    formulaHotspots: orderedHotspots,
    manualReviewItems: orderedManualReview,
    summary,
    sqlPlan: input.sqlPlan ?? null,
    functionsPlan: input.functionsPlan ?? null
  });

  return {
    plan,
    writes: sortByStableKey(writes, (entry) => entry.path)
  };
};

const markdownList = (items: string[]): string[] =>
  items.length === 0 ? ["- None."] : items.map((item) => `- ${item}`);

export const renderGenerationPlanMarkdown = (plan: GenerationPlan): string => {
  const lines: string[] = [];
  lines.push("# Power Exit Generation Plan");
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- Planned files: ${plan.summary.totalPlannedFiles}`);
  lines.push(`- Planned directories: ${plan.summary.totalPlannedDirectories}`);
  lines.push(`- Create: ${plan.summary.creates}`);
  lines.push(`- Overwrite: ${plan.summary.overwrites}`);
  lines.push(`- Skip: ${plan.summary.skips}`);
  lines.push(`- Unchanged: ${plan.summary.unchanged}`);
  lines.push(`- Warnings: ${plan.summary.warnings}`);
  lines.push(`- Unsupported features: ${plan.summary.unsupportedFeatures}`);
  lines.push(`- Formula hotspots: ${plan.summary.formulaHotspots}`);
  lines.push(`- Manual review items: ${plan.summary.manualReviewItems}`);
  lines.push("");
  lines.push("## Planned directories");
  lines.push("");
  lines.push(...markdownList(plan.plannedDirectories));
  lines.push("");
  lines.push("## Planned files");
  lines.push("");
  if (plan.plannedFiles.length === 0) {
    lines.push("- None.");
  } else {
    plan.plannedFiles.forEach((file) => {
      lines.push(
        `- \`${file.path}\` (${file.artifactType}) action=\`${file.action}\` hash=\`${file.contentHash}\` confidence=${file.confidence.toFixed(
          2
        )}`
      );
      if (file.warnings.length > 0) {
        file.warnings.forEach((warning) => lines.push(`  - warning [${warning.code}] ${warning.message}`));
      }
    });
  }
  lines.push("");
  lines.push("## Skipped files");
  lines.push("");
  lines.push(...markdownList(plan.skippedFiles.map((entry) => `\`${entry.path}\`: ${entry.reason}`)));
  lines.push("");
  lines.push("## Overwritten files");
  lines.push("");
  lines.push(
    ...markdownList(
      plan.overwrittenFiles.map(
        (entry) =>
          `\`${entry.path}\` previous=\`${entry.previousContentHash}\` next=\`${entry.nextContentHash}\``
      )
    )
  );
  lines.push("");
  lines.push("## Manual review items");
  lines.push("");
  if (plan.manualReviewItems.length === 0) {
    lines.push("- None.");
  } else {
    plan.manualReviewItems.forEach((item) => {
      lines.push(`- [${item.severity}] ${item.category}: ${item.message}`);
      if (item.relatedPaths.length > 0) {
        lines.push(`  - related paths: ${item.relatedPaths.map((value) => `\`${value}\``).join(", ")}`);
      }
    });
  }
  lines.push("");
  lines.push("## Formula hotspots");
  lines.push("");
  if (plan.formulaHotspots.length === 0) {
    lines.push("- None.");
  } else {
    plan.formulaHotspots.forEach((hotspot) => {
      lines.push(
        `- [${hotspot.severity}] ${hotspot.screen} / ${hotspot.control ?? "(screen)"} / ${hotspot.property} -> ${
          hotspot.formulaBucket
        }`
      );
      lines.push(`  - stub: \`${hotspot.generatedStubName}\``);
      lines.push(`  - formula: \`${hotspot.originalPowerFx.replace(/`/g, "'")}\``);
      lines.push(`  - manual area: ${hotspot.likelyManualImplementationArea}`);
      lines.push(`  - recommendation: ${hotspot.recommendation}`);
    });
  }
  lines.push("");
  lines.push("## SQL plan");
  lines.push("");
  if (!plan.sqlPlan) {
    lines.push("- Not applicable.");
  } else {
    lines.push("### Tables to create");
    lines.push(...markdownList(plan.sqlPlan.tablesToCreate.map((value) => `\`${value}\``)));
    lines.push("");
    lines.push("### Columns to create");
    lines.push(
      ...markdownList(
        plan.sqlPlan.columnsToCreate.map((value) => `\`${value.table}.${value.column}\``)
      )
    );
    lines.push("");
    lines.push("### Foreign keys to create");
    lines.push(...markdownList(plan.sqlPlan.foreignKeysToCreate.map((value) => `\`${value}\``)));
    lines.push("");
    lines.push("### Join tables to create");
    lines.push(...markdownList(plan.sqlPlan.joinTablesToCreate.map((value) => `\`${value}\``)));
    lines.push("");
    lines.push("### Unsupported columns");
    lines.push(...markdownList(plan.sqlPlan.unsupportedColumns.map((value) => `\`${value}\``)));
    lines.push("");
    lines.push("### Unresolved relationships");
    lines.push(...markdownList(plan.sqlPlan.unresolvedRelationships.map((value) => `\`${value}\``)));
    lines.push("");
    lines.push("### Naming collisions");
    lines.push(...markdownList(plan.sqlPlan.namingCollisions.map((value) => `\`${value}\``)));
  }

  if (plan.functionsPlan) {
    lines.push("");
    lines.push("## Functions plan");
    lines.push("");
    lines.push("### Planned functions");
    if (plan.functionsPlan.plannedFunctions.length === 0) {
      lines.push("- None.");
    } else {
      plan.functionsPlan.plannedFunctions.forEach((plannedFunction) => {
        lines.push(
          `- \`${plannedFunction.functionName}\` trigger=\`${plannedFunction.triggerType}\` sourceArtifacts=${plannedFunction.sourceArtifactIds.length}`
        );
      });
    }
    lines.push("");
    lines.push("### Planned adapter files");
    lines.push(
      ...markdownList(
        plan.functionsPlan.plannedAdapterFiles.map(
          (adapterFile) =>
            `\`${adapterFile.filePath}\` (${adapterFile.adapterName}, methods=${adapterFile.methodCount})`
        )
      )
    );
    lines.push("");
    lines.push("### Connector adapter mappings");
    lines.push(
      ...markdownList(
        plan.functionsPlan.connectorAdapterMappings.map(
          (mapping) =>
            `${mapping.connectorKey} -> \`${mapping.adapterFilePath}\` (${mapping.actionNames.join(", ") || "no actions"})`
        )
      )
    );
    lines.push("");
    lines.push("### Trigger strategy");
    lines.push(
      ...markdownList(
        plan.functionsPlan.triggerStrategy.map(
          (trigger) =>
            `${trigger.functionName}: ${trigger.triggerClassification} -> ${trigger.strategy}${
              trigger.warning ? ` (warning: ${trigger.warning})` : ""
            }`
        )
      )
    );
    lines.push("");
    lines.push("### Handler signatures");
    lines.push(
      ...markdownList(
        plan.functionsPlan.handlerSignatures.map(
          (signature) =>
            `${signature.functionName}: ${signature.exportedHandler}(${signature.requestType}, ${signature.contextType}) => ${signature.responseType}`
        )
      )
    );
    lines.push("");
    lines.push("### Unsupported actions");
    lines.push(
      ...markdownList(
        plan.functionsPlan.unsupportedActions.map(
          (action) =>
            `${action.flowName}.${action.actionName} (\`${action.actionType}\`)`
        )
      )
    );
    lines.push("");
    lines.push("### Unresolved dependencies");
    lines.push(
      ...markdownList(
        plan.functionsPlan.unresolvedDependencies.map(
          (dependency) =>
            `${dependency.referenceType}:${dependency.referenceName}`
        )
      )
    );
    lines.push("");
    lines.push("### Unresolved adapter requirements");
    lines.push(
      ...markdownList(
        plan.functionsPlan.unresolvedAdapterRequirements.map(
          (requirement) => `${requirement.connectorKey}: ${requirement.requirement}`
        )
      )
    );
    lines.push("");
    lines.push("### Manual review hotspots");
    lines.push(
      ...markdownList(
        plan.functionsPlan.manualReviewHotspots.map(
          (hotspot) => `[${hotspot.severity}] ${hotspot.message}`
        )
      )
    );
    lines.push("");
    lines.push("### Deployment readiness");
    lines.push(`- scaffoldOnly: ${plan.functionsPlan.deploymentReadiness.scaffoldOnly}`);
    lines.push(`- needsConfig: ${plan.functionsPlan.deploymentReadiness.needsConfig}`);
    lines.push(`- needsManualLogic: ${plan.functionsPlan.deploymentReadiness.needsManualLogic}`);
    lines.push(`- blocked: ${plan.functionsPlan.deploymentReadiness.blocked}`);
  }

  lines.push("");
  lines.push("Review `generation-plan.json` and resolve skipped/manual items before committing generated files.");

  return `${lines.join("\n")}\n`;
};

export const serializeGenerationPlan = (plan: GenerationPlan): string => `${stableStringify(plan)}\n`;

export const GENERATED_FILE_MARKER_TEXT = markerTextPlain;
